spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@gmail.com
spring.mail.password=dummypassword
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false